### ISSUE TITLE
Issue的这本提示Pypdf2出错

### ISSUE THREAD

**Issue by rffaxs** [301Moved/ScienceDecrypting#12]
Issue的这本书，https://book.sciencereading.cn/shop/book/Booksimple/show.do?id=BA5AC0961B9ED54E9E053010B0A0A2F0D000下载测试报错。
Traceback (most recent call last):
  File "gui.py", line 36, in decrypt_background
  File "decrypt.py", line 114, in decrypt_file
  File "PyPDF2\pdf.py", line 482, in write
  File "PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
  File "PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
  File "PyPDF2\pdf.py", line 586, in _sweepIndirectReferences
  File "PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
  File "PyPDF2\pdf.py", line 556, in _sweepIndirectReferences
  File "PyPDF2\pdf.py", line 586, in _sweepIndirectReferences
  File "PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
  File "PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
  File "PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
  File "PyPDF2\pdf.py", line 577, in _sweepIndirectReferences
  File "utils.py", line 62, in getObject
  File "PyPDF2\generic.py", line 66, in readObject
  File "utils.py", line 191, in myReadFromStream
PyPDF2.utils.PdfReadError: Unable to find 'endstream' marker after stream at byte 0x9e83b2e.

**鉴于Pypdf2的诸多问题，是否能考虑采取其他PDF库，如[pikepdf](https://pypi.org/project/pikepdf/)等**

**Comment by 301Moved** [comment]
看起来可以，早知道有这个库就不折腾PyPDF2了
