### ISSUE TITLE
科学文库 解密失败，帮忙看看，谢谢

### ISSUE THREAD

**Issue by ayumi106** [301Moved/ScienceDecrypting#20]
开始解密 C:/Users/Administrator/Downloads/仓储与配送管理  _  2版.pdf
[Log] 解析源文件....
[Log] 请求密钥...
[Error] 解密失败，未知错误:  HTTPConnectionPool(host='159.226.29.160', port=80): Max retries exceeded with url: /DRMMngr/auth.aspx?pn=scienceReading (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026CB1A51D30>: Failed to establish a new connection: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。',))

如果你需要帮助，请复制以下信息到GitHub ( https://github.com/301Moved/ScienceDecrypting/issues/new ) 上提交Issue
----------------------------------------------------------------
Traceback (most recent call last):
  File "urllib3\connection.py", line 170, in _new_conn
  File "urllib3\util\connection.py", line 96, in create_connection
  File "urllib3\util\connection.py", line 86, in create_connection
OSError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 706, in urlopen
  File "urllib3\connectionpool.py", line 394, in _make_request
  File "urllib3\connection.py", line 234, in request
  File "http\client.py", line 1239, in request
  File "http\client.py", line 1285, in _send_request
  File "http\client.py", line 1234, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 964, in send
  File "urllib3\connection.py", line 200, in connect
  File "urllib3\connection.py", line 182, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000026CB1A51D30>: Failed to establish a new connection: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 449, in send
  File "urllib3\connectionpool.py", line 756, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='159.226.29.160', port=80): Max retries exceeded with url: /DRMMngr/auth.aspx?pn=scienceReading (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026CB1A51D30>: Failed to establish a new connection: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui.py", line 35, in decrypt_background
  File "decrypt.py", line 107, in decrypt_file
  File "decrypt.py", line 46, in request_password
  File "requests\api.py", line 117, in post
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='159.226.29.160', port=80): Max retries exceeded with url: /DRMMngr/auth.aspx?pn=scienceReading (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026CB1A51D30>: Failed to establish a new connection: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。',))

**Comment by ayumi106** [comment]
自己搞定了，原来是火绒的原因。我把火狐的联网控制关闭就好了
