### ISSUE TITLE
解密失败，未知错误

### ISSUE THREAD

**Issue by liushuiguadanbo** [301Moved/ScienceDecrypting#23]
大佬你好，以下是我在使用您工具时出现的错误目录，烦请您指点一下我，谢谢。

Traceback (most recent call last):
  File "urllib3\connection.py", line 170, in _new_conn
  File "urllib3\util\connection.py", line 96, in create_connection
  File "urllib3\util\connection.py", line 86, in create_connection
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 706, in urlopen
  File "urllib3\connectionpool.py", line 394, in _make_request
  File "urllib3\connection.py", line 234, in request
  File "http\client.py", line 1239, in request
  File "http\client.py", line 1285, in _send_request
  File "http\client.py", line 1234, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 964, in send
  File "urllib3\connection.py", line 200, in connect
  File "urllib3\connection.py", line 182, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001B189F52DA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 449, in send
  File "urllib3\connectionpool.py", line 756, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=6070): Max retries exceeded with url: http://159.226.29.160/DRMMngr/auth.aspx?pn=scienceReading (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B189F52DA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui.py", line 35, in decrypt_background
  File "decrypt.py", line 107, in decrypt_file
  File "decrypt.py", line 46, in request_password
  File "requests\api.py", line 117, in post
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 510, in send
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=6070): Max retries exceeded with url: http://159.226.29.160/DRMMngr/auth.aspx?pn=scienceReading (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B189F52DA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))

**Comment by 301Moved** [comment]
是不是没网，或者什么安全软件限制联网权限了

**Comment by liushuiguadanbo** [comment]
> 是不是没网，或者什么安全软件限制联网权限了

好像不是耶 可以的话麻烦大佬试一下在你那里是不是可以解密呢？
网址是：https://book.sciencereading.cn/shop/book/Booksimple/show.do?id=BC13EB9F994133A2028BC8AD1A80099B4000

**Comment by 301Moved** [comment]
开了全局代理，代理到 127.0.0.1:6070 了吧，看下windows的代理设置。

**Comment by liushuiguadanbo** [comment]
> 开了全局代理，代理到 127.0.0.1:6070 了吧，看下windows的代理设置。

是这样的，谢谢大佬，具体解决方法可以参见
https://blog.csdn.net/LQ_qing/article/details/100373733
