### ISSUE TITLE
解密科学文库书籍会出现解密报错和目录缺失

### ISSUE THREAD

**Issue by HITers2018** [301Moved/ScienceDecrypting#5]
1. 在尝试解密[研究生数学建模精品案例
](https://book.sciencereading.cn/shop/book/Booksimple/show.do?id=BBD8EA0AF2180405DAEB6926B802B4923000)解密时报错，输出的文件也无法打开，报错提示：
`Traceback (most recent call last):
  File "C:\Users\abc\Desktop\decrypt.py", line 242, in <module>
    main()
  File "C:\Users\abc\Desktop\decrypt.py", line 237, in main
    decrypt_file(options.src, options.dst)
  File "C:\Users\abc\Desktop\decrypt.py", line 213, in decrypt_file
    output.write(outputStream)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\pdf.py", line 482, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\pdf.py", line 556, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  [Previous line repeated 1 more time]
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\pdf.py", line 577, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "C:\Users\abc\Desktop\decrypt.py", line 82, in getObject
    retval = readObject(self.stream, self)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\generic.py", line 66, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\generic.py", line 632, in readFromStream
    raise utils.PdfReadError("Unable to find 'endstream' marker after stream at byte %s." % utils.hexStr(stream.tell()))
PyPDF2.utils.PdfReadError: Unable to find 'endstream' marker after stream at byte 0x1095ae5.`

2. 在尝试解密[WOLFRAM MATHEMATICA 实用编程指南](https://book.sciencereading.cn/shop/book/Booksimple/show.do?id=B6FFB034E3E1E11CCE053020B0A0ACCB2000)时，解密无报错，但目录丢失（原文件经CAJViewer打开目录正常显示）。

**Comment by Eumeryx** [comment]
我使用 `PyPDF2` 的这个 PR： https://github.com/mstamy2/PyPDF2/pull/250
并将其中第 628 行的 `extra` 设为
```
extra = stream.read(100)
```
成功解密了 @HITers2018  提供的样本。

但这个对 `PyPDF2` 的修改，我不太好合并进现有的代码结构， @301Moved  是否考虑把 `PyPDF2` 的代码合并进来？

**Comment by rffaxs** [comment]
测试了，采用此方法正常解码。
但是目录采用修改方案，“研究生数学建模精品案例”正常，但是如“[大学物理（第三版）上册](https://book.sciencereading.cn/shop/book/Booksimple/show.do?id=B07EA9B9D5DE64C30819A625EC63D6B67000)”无法解码，目录模块异常，Traceback (most recent call last):
  File "decrypt.py", line 254, in <module>
    main()
  File "decrypt.py", line 249, in main
    decrypt_file(options.src, options.dst)
  File "decrypt.py", line 222, in decrypt_file
    bookmark(input_.outlines, None, output, input_)
  File "decrypt.py", line 170, in bookmark
    prev_mark = output.addBookmark(
  File "XXX\Python38-32\lib\site-packages\PyPDF2\pdf.py", line 719, in addBookmark
    dest = Destination(NameObject("/"+title + " bookmark"), pageRef, NameObject(fit), *zoomArgs)
  File "XXX\Python38-32\lib\site-packages\PyPDF2\generic.py", line 1058, in __init__
    (self[NameObject("/Left")], self[NameObject("/Top")],
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by Eumeryx** [comment]
> 测试了，采用此方法正常解码。
> 但是目录采用修改方案，“研究生数学建模精品案例”正常，但是如“[大学物理（第三版）上册](https://book.sciencereading.cn/shop/book/Booksimple/show.do?id=B07EA9B9D5DE64C30819A625EC63D6B67000)”无法解码，目录模块异常，Traceback (most recent call last):
> File "decrypt.py", line 254, in
> main()
> File "decrypt.py", line 249, in main
> decrypt_file(options.src, options.dst)
> File "decrypt.py", line 222, in decrypt_file
> bookmark(input_.outlines, None, output, input_)
> File "decrypt.py", line 170, in bookmark
> prev_mark = output.addBookmark(
> File "XXX\Python38-32\lib\site-packages\PyPDF2\pdf.py", line 719, in addBookmark
> dest = Destination(NameObject("/"+title + " bookmark"), pageRef, NameObject(fit), *zoomArgs)
> File "XXX\Python38-32\lib\site-packages\PyPDF2\generic.py", line 1058, in **init**
> (self[NameObject("/Left")], self[NameObject("/Top")],
> ValueError: not enough values to unpack (expected 3, got 0)

@rffaxs 现在目录应该正常了。

**Comment by HITers2018** [comment]
> 我使用 `PyPDF2` 的这个 PR： [mstamy2/PyPDF2#250](https://github.com/mstamy2/PyPDF2/pull/250)
> 并将其中第 628 行的 `extra` 设为
> 
> ```
> extra = stream.read(100)
> ```
> 
> 成功解密了 @HITers2018 提供的样本。
> 
> 但这个对 `PyPDF2` 的修改，我不太好合并进现有的代码结构， @301Moved 是否考虑把 `PyPDF2` 的代码合并进来？

对于我在issue中提到的[第二本书](https://book.sciencereading.cn/shop/book/Booksimple/show.do?id=B6FFB034E3E1E11CCE053020B0A0ACCB2000)，新提交的代码仍会报错，报错提示如下：
`[Error] 未知错误:  not enough values to unpack (expected 3, got 2)
----------------------------------------------------------------
Traceback (most recent call last):
  File "D:\decrypt.py", line 254, in <module>
    main()
  File "D:\decrypt.py", line 249, in main
    decrypt_file(options.src, options.dst)
  File "D:\decrypt.py", line 222, in decrypt_file
    bookmark(input_.outlines, None, output, input_)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\pdf.py", line 1391, in <lambda>
    outlines = property(lambda self: self.getOutlines(), None, None)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\pdf.py", line 1419, in getOutlines
    self._namedDests = self.getNamedDestinations()
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\pdf.py", line 1376, in getNamedDestinations
    self.getNamedDestinations(kid.getObject(), retval)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\pdf.py", line 1385, in getNamedDestinations
    dest = self._buildDestination(key, val)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\pdf.py", line 1489, in _buildDestination
    return Destination(title, page, typ, *array)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyPDF2\generic.py", line 1064, in __init__
    (self[NameObject("/Left")], self[NameObject("/Top")],
ValueError: not enough values to unpack (expected 3, got 2)`

**Comment by Eumeryx** [comment]
@HITers2018 看起来是无法获取大纲，你能向我提供第二本书的样本吗？我使用的帐号无法下载这本书。

**Comment by HITers2018** [comment]
> @HITers2018 看起来是无法获取大纲，你能向我提供第二本书的样本吗？我使用的帐号无法下载这本书。

这是第二本书，[阿里云盘链接](https://github.com/301Moved/ScienceDecrypting/issues/5#issuecomment-898504852)。

**Comment by HITers2018** [comment]
> @HITers2018 看起来是无法获取大纲，你能向我提供第二本书的样本吗？我使用的帐号无法下载这本书。

这是第二本书，[阿里云盘分享链接](https://www.aliyundrive.com/s/iLWtgYiKofs)。

**Comment by Eumeryx** [comment]
> ## 对于我在issue中提到的[第二本书](https://book.sciencereading.cn/shop/book/Booksimple/show.do?id=B6FFB034E3E1E11CCE053020B0A0ACCB2000)，新提交的代码仍会报错，报错提示如下：

@HITers2018 这个 PR： #7 直接复制了目录。

**Comment by 301Moved** [comment]
> 我使用 `PyPDF2` 的这个 PR： [mstamy2/PyPDF2#250](https://github.com/mstamy2/PyPDF2/pull/250)
> 并将其中第 628 行的 `extra` 设为
> 
> ```
> extra = stream.read(100)
> ```
> 
> 成功解密了 @HITers2018 提供的样本。
> 
> 但这个对 `PyPDF2` 的修改，我不太好合并进现有的代码结构， @301Moved 是否考虑把 `PyPDF2` 的代码合并进来？

PyPDF2的代码比较多，合并进来之后不容易区分出来哪些是魔改过的内容，目前我还是倾向于手动patch PyPDF2库的方式
